apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1  # You can increase this if needed for scaling
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: fabricioveronez/api:latest  # Ensure a valid tag is specified
          ports:
            - containerPort: 8080
          resources: {}  # Empty resources, can be defined later if needed
          env:
            - name: Mongo_Host
              value: "mongo-service"
            - name: Mongo_User
              value: "mongodbuser"
            - name: Mongo_Password
              value: "mongodbpwd"
            - name: Mongo_Port
              value: "27017"
            - name: Mongo_DataBase
              value: "admin"