apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
    - port: 80          # Exposed externally
      targetPort: 8080  # Where your API container listens
      protocol: TCP
  selector:
    app: api            # This must match the labels on your API pods